---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels: {}
  name: mowtalk
spec:
  type: ClusterIP
  ports:
    # make the service available on this port
    - port: 80
      name: unsecure
      targetPort: 80
      protocol: TCP
  selector:
    app: mowtalk
