version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mow-help-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - mow-help-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1-php7.4-fpm-alpine
    container_name: mow-help-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WP_DB_HOST: 'db:3306'
      WP_DB_USER: $WP_DB_USER
      WP_DB_PASSWORD: $WP_DB_PASSWORD
      WP_DB_NAME: wordpress
      SPACES_ACCESS_KEY_ID: $SPACES_ACCESS_KEY_ID
      SPACES_SECRET_ACCESS_KEY: $SPACES_SECRET_ACCESS_KEY
      DOMAIN_CURRENT_SITE: mowtalk.dev.itjl.xyz;
    volumes:
      - ./public/wordpress:/var/www/html/blog
    networks:
      - mow-help-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: mow-help-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public/wordpress:/var/www/html/blog
      - ./conf/nginx/dev:/etc/nginx/conf.d
    networks:
      - mow-help-network

volumes:
  dbdata:

networks:
  mow-help-network:
    driver: bridge
